name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script. 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Trigger the main workflow of the Cypress UI tests repository
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'Mercell',
              repo: 'tricom.ia.uitests',
              workflow_id: 'main.yml',
              inputs: {
              tags: ${{ steps.get-tags.outputs.tags }}
              },
            })
            console.log(result);
            } catch(error) {
            console.error(error);
            core.setFailed(error);
            }
