name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_world:
    name: hello-world
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script. 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  cypress_run:
    name: cypress run
    runs-on: ubuntu-latest
    
    steps:
		- uses: actions/checkout@v2
	
		- name: Trigger Workflow and Wait
		  uses: convictional/trigger-workflow-and-wait@v1.6.0
		  with:
			owner: 
			repo: 
			github_token: 
			wait_interval:
			workflow_file_name: 
			propagate_failure:
			wait_workflow:


