name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script. 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Trigger the main workflow of the Cypress UI tests repository and wait for feedback
        uses: convictional/trigger-workflow-and-wait@v1.6.0
		    with:
		      owner: Mercell
		      repo: tricom.ia.uitests
		      github_token: ${{ secrets.PAT_TOKEN }}
		      workflow_file_name: main.yml
		      wait_interval: 60
		      propagate_failure: true
